CREATE DATABASE ESTADIO;

USE ESTADIO;

CREATE TABLE CADEIRA(
	CAD_ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE FILEIRA(
	FIL_ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE DIA(
	DIA_ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE SETOR(
	SET_ID INT AUTO_INCREMENT PRIMARY KEY,
	SET_DESCRICAO VARCHAR(15)
);

CREATE TABLE SETOR_DIA(
	SD_ID INT AUTO_INCREMENT PRIMARY KEY,
	SD_SETOR INT NOT NULL,
	SD_DIA INT NOT NULL,
	SD_PRECO DOUBLE NOT NULL,
	
	CONSTRAINT FK_SETOR_DIA FOREIGN KEY (SD_SETOR)
	REFERENCES SETOR (SET_ID),
	
	CONSTRAINT FK_DIA_SETOR FOREIGN KEY (SD_DIA)
	REFERENCES DIA (DIA_ID)
);

CREATE TABLE LUGAR(
	LUG_ID 		INT AUTO_INCREMENT PRIMARY KEY,
	LUG_CADEIRA INT NOT NULL,
	LUG_FILEIRA INT NOT NULL,
	LUG_SETOR	INT NOT NULL,
	LUG_DIA		INT NOT NULL,
	
	CONSTRAINT FK_LUGAR_CADEIRA FOREIGN KEY (LUG_CADEIRA)
	REFERENCES CADEIRA (CAD_ID),
	
	CONSTRAINT FK_CADEIRA_FILEIRA FOREIGN KEY (LUG_FILEIRA)
   REFERENCES FILEIRA (FIL_ID),
   
   CONSTRAINT FK_DIA_LUGAR FOREIGN KEY (LUG_DIA)
   REFERENCES DIA (DIA_ID),
   
   CONSTRAINT FK_LUGAR_SETOR FOREIGN KEY (LUG_SETOR)
   REFERENCES SETOR(SET_ID)
   
);

CREATE TABLE CLIENTE(
	CLI_ID 		INT AUTO_INCREMENT PRIMARY KEY,
	CLI_NOME 	VARCHAR(25) NOT NULL,
	CLI_EMAIL 	VARCHAR(35)
);

CREATE TABLE INGRESSO(
	ING_ID 		INT AUTO_INCREMENT PRIMARY KEY,
	ING_CLIENTE INT NOT NULL,
	ING_LUGAR 	INT NOT NULL,
	ING_DATA		TIMESTAMP,
	
	CONSTRAINT FK_INGRESSO_CLIENTE FOREIGN KEY (ING_CLIENTE)
	REFERENCES CLIENTE (CLI_ID),
	
	
	CONSTRAINT FK_INGRESSO_LUGAR FOREIGN KEY (ING_LUGAR)
	REFERENCES LUGAR (LUG_ID)
);